spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

server:
  port: 6001


management:
  endpoint:
    health:
      enabled: true




